config/routes.rb
Rails.application.routes.draw do
  resources :categories

  resources :reviews

  get 'examples/show/:id' => 'examples#show'

  get '/examples/view/:id' => 'examples#view'

  get '/examples/json/:id' => 'examples#json'

  get '/examples/svgpage' => 'examples#svgpage'

  get '/examples/cssBMO' => 'examples#cssBMO'

  resources :pages

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'pages#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products, :dependent =>  :destroy
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_attached_file :image,
                    :styles => {
                        :thumb => '100x100#',
                        :small => '150x150>',
                        :medium => '200x200>',
                        :large => '1500x770>'
                    }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  attr_accessor :delete_image
  before_validation { self.image.clear if self.delete_image == '1' }

  def page_type_enum
    [['HTML',0], ['Text',1],['Image',2]]
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews, :inverse_of => :product
  belongs_to :category

  has_attached_file :image,
                    :styles => {
                        :thumb => "100x100#",
                        :small  => "260x274>",
                        :medium => "458x482" },
                    :default_url => 'missing_small.jpg'
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  # add a delete_<asset_name> method:
  attr_accessor :delete_image
  before_validation { self.image.clear if self.delete_image == '1' }

  def mainImage_url
    image.url(:medium)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :thumb)
    end
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  layout 'examples'
  def show
    @category = Category.find(params[:id])
    @products = @category.products.all
  end

  def view
    @product = Product.find(params[:id])
    @reviews = @product.reviews.all
    @thumb = Product.find([3,4,5,6])

    respond_to do |format|
      format.html { render :layout => !request.xhr? }
      # other formats
    end
  end

  def svgpage
    render :layout => false
  end

  def cssBMO
    render :layout => false
  end

  def json
    @product = Product.find(params[:id])
    render :json => @product.to_json(:methods => [:mainImage_url])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all.order(:number)
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:title, :page_type, :body, :image, :html, :number, :custom_css, :custom_js)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
    respond_to do |format|
      format.html { render :layout => nil if request.xhr? }
    end
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:name, :title, :text, :score, :product_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :thumb %><br>
    <%= f.text_field :thumb %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Thumb</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.thumb %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Thumb:</strong>
  <%= @category.thumb %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/examples/show.html.erb
<ol class="breadcrumb">
  <li><a href="#">Start</a></li>
  <li>Kleidung</li>
</ol>
<div class="row">
  <% @products.each do |product| %>
      <div class="col-sm-6 col-md-3 thumb-element disabled">
        <a href="#" onclick="getProduct('http://localhost:3000/examples/view/<%= product.id %>');return false">
        <div class="thumbnail">
          <%= image_tag(product.image.url(:small)) %>
          <div class="caption">
            <h3 style="min-height: 52px;"><%= product.name %></h3>
            <p>
            <div class="price">€<%= number_with_precision(product.price, precision: 2 ) %></div>
            </p>
            <p><a href="#" class="btn btn-default addToCart min" role="button" onclick="addToCart(this,<%= product.id %>,'min');">In den Warenkorb</a></p>
          </div>
        </div>
        </a>
      </div>
  <% end %>
</div>
<script type="text/javascript" charset="utf-8" src="<%= path_to_javascript 'custom/show'%>"></script>

app/views/examples/view.erb
#encoding: utf-8
<ol class="breadcrumb">
  <li><a href="#">Start</a></li>
  <li><a href="#">Kleidung</a></li>
  <li>Supergeiler Schlüpper</li>
</ol>
<div class="row">
  <div class="col-md-5">
    <%= image_tag(@product.image.url(:medium), :class => "img-responsive", :id =>'main-img' ) %>
    <div class="img-loader loder-container" style="display: none;">
      <svg width="300px" height="200px" viewBox="0 0 187.3 93.7" preserveAspectRatio="xMidYMid meet">
        <path style="-webkit-filter:url(#f2)" stroke="#777777" id="outline" fill="none" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" d="
				M93.9,46.4c9.3,9.5,13.8,17.9,23.5,17.9s17.5-7.8,17.5-17.5s-7.8-17.6-17.5-17.5c-9.7,0.1-13.3,7.2-22.1,17.1
				c-8.9,8.8-15.7,17.9-25.4,17.9s-17.5-7.8-17.5-17.5s7.8-17.5,17.5-17.5S86.2,38.6,93.9,46.4z" />
        <path id="outline-bg" opacity="0.05" fill="none" stroke="#777777" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" d="
				M93.9,46.4c9.3,9.5,13.8,17.9,23.5,17.9s17.5-7.8,17.5-17.5s-7.8-17.6-17.5-17.5c-9.7,0.1-13.3,7.2-22.1,17.1
				c-8.9,8.8-15.7,17.9-25.4,17.9s-17.5-7.8-17.5-17.5s7.8-17.5,17.5-17.5S86.2,38.6,93.9,46.4z" />
      </svg>
    </div>
  </div>
  <div class="col-md-7 pull-right addToCart-block">
    <div class="row">
      <div class="col-md-9 col-xs-12">
        <h1><%= @product.name %></h1>
      </div>
      <div class="col-md-3 col-xs-12">
        <div class="price">€<span id="main-price"><%= number_with_precision(@product.price, precision: 2) %></span></div>
      </div>
    </div>
    <div class="row review">
      <ul class="pull-left">
        <li class="glyphicon glyphicon-star-empty"></li>
        <li class="glyphicon glyphicon-star-empty"></li>
        <li class="glyphicon glyphicon-star-empty"></li>
        <li class="glyphicon glyphicon-star-empty"></li>
        <li class="glyphicon glyphicon-star-empty"></li>
        <li class="glyphicon glyphicon-star-empty"></li>
      </ul>
      <span class="pull-left">(0 Bewertungen)</span>
    </div>
    <div class="row">
      <div class="col-md-12">
        <blockquote id="shortdesc"><%= simple_format(@product.shortdesc) %>
        </blockquote>

      </div>
    </div>
    <div class="row options">
      <div class="btn-group ">
        <button class="btn btn-default btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span id="model-container"><%= @product.hero %></span>
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li>
            <a data-url="/examples/json/1">Batman</a>
          </li>
          <li>
            <a data-url="/examples/json/2">Superman</a>
          </li>
        </ul>
      </div>
    </div>
    <div class="row button-box">
      <div class="col-md-4">
        <input id="cart-quantity" class="cart-quantity" type="number" min="1" value="1" name="quantity">
      </div>
      <div class="col-md-8">
        <button class="btn btn-default addToCart" id="addToCart-button" type="submit" onclick="addToCart(this,1,'');">
          <span>In den Warenkorb</span>
        </button>
        <svg width="42" height="42" style="display:none; position: absolute; left: 45%; top: 0%; z-index: 2000;">
          <circle cx="21" cy="21" r="21" fill="#FF5722" />
        </svg>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <div class="page-header">
      <h3>Produktinformationen</h3>
    </div>
    <span id="description" >
   <%= simple_format(@product.description) %>
    </span>
  </div>
  <div class="col-md-6">
    <div class="page-header">
      <h3>Kundenbewertungen</h3>
    </div>
    Noch keine Bewertungen für dieses Produkt.
  </div>
</div>
<div class="row border">
  <div class="page-header">
    <h3>Haben Sie diese Artikel schon gesehen?</h3>
  </div>
  <div class="row">
    <% @thumb.each do |thumb| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= image_tag(thumb.image.url(:small)) %>
        <div class="caption">
          <h3><%= thumb.name %></h3>
          <p>
          <div class="price">€<%= number_with_precision(thumb.price, precision: 2) %></div>
          </p>
          <p style="position:relative;"><a href="#" class="btn btn-default addToCart min" role="button" onclick="addToCart(this,<%= thumb.id %>,'min');">In den Warenkorb</a><svg style="display: none;" width="42" height="42">
            <circle cx="21" cy="21" r="21" fill="#FF5722" />
          </svg></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<script type="text/javascript" charset="utf-8" src="<%= path_to_javascript 'custom/view'%>"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BaPresNonprint</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-hijacking="off" data-animation="scaleDown">
<%= yield %>
<nav>
  <ul class="cd-vertical-nav">
    <li><a href="#0" class="cd-prev inactive">Next</a></li>
    <li><a href="#0" class="cd-next">Prev</a></li>
  </ul>
</nav> <!-- .cd-vertical-nav -->
</body>
</html>

app/views/layouts/examples.erb
<!DOCTYPE html>

<html>
<head>
  <link rel="stylesheet" href="<%= path_to_stylesheet 'examples' %>">
  <script type="text/javascript" charset="utf-8" src="<%= path_to_javascript 'examples'%>"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => 'layouts/examples_partials/examples_head' %>
<div class="container main-wrapper">
  <div id="content-main">
  <%= yield %>
  </div>
  <div class="main-loader loder-container" style="display: none;">
    <svg width="300px" height="200px" viewBox="0 0 187.3 93.7" preserveAspectRatio="xMidYMid meet">
      <path style="-webkit-filter:url(#f2)" stroke="#777777" id="outline" fill="none" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" d="
				M93.9,46.4c9.3,9.5,13.8,17.9,23.5,17.9s17.5-7.8,17.5-17.5s-7.8-17.6-17.5-17.5c-9.7,0.1-13.3,7.2-22.1,17.1
				c-8.9,8.8-15.7,17.9-25.4,17.9s-17.5-7.8-17.5-17.5s7.8-17.5,17.5-17.5S86.2,38.6,93.9,46.4z" />
      <path id="outline-bg" opacity="0.05" fill="none" stroke="#777777" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" d="
				M93.9,46.4c9.3,9.5,13.8,17.9,23.5,17.9s17.5-7.8,17.5-17.5s-7.8-17.6-17.5-17.5c-9.7,0.1-13.3,7.2-22.1,17.1
				c-8.9,8.8-15.7,17.9-25.4,17.9s-17.5-7.8-17.5-17.5s7.8-17.5,17.5-17.5S86.2,38.6,93.9,46.4z" />
    </svg>
  </div>
  <%= render :partial => 'layouts/examples_partials/examples_footer' %>
</div>
<div class="overlay">
  <span class="overlay-inner">
    <span id="closeButton" class="fa fa-times-circle-o fa-lg"></span>
    <div id="overlay-content">
      <form name="loginForm">
        <div class="form-group email-group">
          <label for="beispielFeldEmail1">Name</label>
          <input name="femail" type="email" class="form-control" id="beispielFeldEmail1" placeholder="Email-Adresse">
        </div>
        <div class="form-group pw-group">
          <label for="beispielFeldPasswort1">Passwort</label>
          <input name="fpassword" type="password" class="form-control" id="beispielFeldPasswort1" placeholder="Passwort">
        </div>
        <div class="checkbox">
          <label>
            <input type="checkbox"> Angemeldet bleiben?
          </label>
        </div>
        <button type="button" class="btn btn-default" onclick="loginAction(); return false;" >Login</button>
      </form>
    </div>
  </span>
</div>
<script type="text/javascript" charset="utf-8" src="<%= path_to_javascript 'anijs/anijs-min'%>"></script>
<script type="text/javascript" charset="utf-8" src="<%= path_to_javascript 'anijs/anijs-helper-dom-min'%>"></script>
<script type="text/javascript" charset="utf-8" src="<%= path_to_javascript 'anijs/anijs-helper-scrollreveal-min'%>"></script>
<script type="text/javascript" charset="utf-8" src="<%= path_to_javascript 'anijs/anijs-jquery-event-system-min'%>"></script>
<script type="text/javascript" charset="utf-8" src="<%= path_to_javascript 'greensock/TweenMax.min'%>"></script>
<script type="text/javascript" charset="utf-8" src="<%= path_to_javascript 'greensock/DrawSVGPlugin.min'%>"></script>
<script type="text/javascript" charset="utf-8" src="<%= path_to_javascript 'custom/main'%>"></script>
</body>
</html>

app/views/layouts/examples_partials/_examples_footer.erb
#encoding: utf-8
<div class="row footer">
  <div class="row-height">
    <div class="col-xs-12 col-sm-4 col-sm-height col-sm-middle">
      <div class="inside inside-full-height">
        <div class="content">
          <div class="footer-title">Kontakt</div>
          <ul class="list-inline">
            <li><a href="#" class="fa fa-facebook fa-3x"></a></li>
            <li><a href="#" class="fa fa-twitter fa-3x"></a></li>
            <li><a href="#" class="fa fa-instagram fa-3x"></a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4 col-sm-height col-sm-middle">
      <div class="inside inside-full-height">
        <div class="content">
          <div class="footer-title">Navigation</div>
          <div class="row">
            <div class="col-md-6">
              <ul>
                <li><a href="#">Start</a></li>
                <li><a href="#">Kleidung</a></li>
                <li><a href="#">Figuren</a></li>
                <li><a href="#">Bücher</a></li>
              </ul>
            </div>
            <div class="col-md-6">
              <ul>
                <li><a href="#">Filme</a></li>
                <li><a href="#">Gadgets</a></li>
                <li><a href="#">LOL</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4 col-sm-height col-sm-middle">
      <div class="inside inside-full-height">
        <div class="content logo">
          WTF
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/examples_partials/_examples_head.erb
#encoding: utf-8
<!-- Fixed Navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Navigation ein-/ausblenden</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">WTF</a>
      </div>
      <ul class="nav navbar-nav navbar-right top-links">
        <li>
          <a id="login-form" class="glyphicon glyphicon-user"> Login</a>
        </li>
        <li class="cart">
          <div class="cart-summery">
            <span class="price">€<span>0,00</span></span>
            <span class="count">0 Produkte</span>
          </div>
          <a>
            <div class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></div>
          </a>
        </li>
      </ul>
    </div>
    <div class="container-fluid bottom-nav">
      <div class="container">
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-center">
            <li class="active"><a href="http://localhost:3000/examples/1">Kleidung</a></li>
            <li><a href="http://localhost:3000/examples/2">Figuren</a></li>
            <li><a href="http://localhost:3000/examples/3">Bücher</a></li>
            <li><a href="http://localhost:3000/examples/4">Filme</a></li>
            <li><a href="http://localhost:3000/examples/5">Gadgets</a></li>
            <li><a href="http://localhost:3000/examples/6">LOL</a></li>
            <li><a id="searchButton" class="glyphicon glyphicon-search" aria-hidden="true"> Suche</a></li>
          </ul>
        </div>
        <!--/.nav-collapse -->
      </div>
    </div>
    <div class="container" style="display:flex;justify-content:center;align-items:center; background: transparent">
      <input id="searchbar" type="text" placeholder="Suchen...">
    </div>
  </nav>

app/views/pages/_page.erb
# encoding: utf-8

<span class="content-inner">

  <% if page.page_type != 0 %>

      <%= case page.page_type
            when 1 then ('<h1>'+page.title+'</h1><div class="text">'+page.body+'</div>').html_safe
            when 2 then ('<div class="image-wrapper">'+image_tag(page.image.url(:large), :class => 'img-responsive')+'</div>').html_safe
            else        "NULL"
          end %>
    <% else %>
      <section class="facade-minimal" data-url="/examples/<%= page.html %>">
        <div class="reload-button"></div>
        <iframe data-frameSrc="/examples/<%= page.html %>" frameborder="0" width="100%" height="750"></iframe>
      </section>
    <% end %>
  <% if page.page_type != 0 %>
  <div class="content-bottom">
    <span class="left">
      Ben Wunderlich <%= Date.today.strftime('%d.%m.%Y') %>
    </span>
    <span class="right">
       Folie: <%= page.number %>
    </span>
  </div>
<% end %>
</span>
<% if page.custom_js.present? %>
    <script>
      $(document).ready(function(){
          <%= page.custom_js.html_safe %>
      });
    </script>
<% end %>

app/views/pages/index.html.erb
<% @pages.each do |page| %>
    <section class="cd-section <%= 'visible' if page.number == 1 %>" data-page="<%= page.number %>">
      <div>
        <span class="content">
          <%= render :partial => 'pages/page', :object => page %>
        </span>
      </div>
    </section>
<% end %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Page type:</strong>
  <%= @page.page_type %>
</p>

<p>
  <strong>Body:</strong>
  <%= @page.body %>
</p>

<p>
  <strong>Image:</strong>
  <%= @page.image %>
</p>

<p>
  <strong>Html:</strong>
  <%= @page.html %>
</p>

<p>
  <strong>Number:</strong>
  <%= @page.number %>
</p>

<p>
  <strong>Custom css:</strong>
  <%= @page.custom_css %>
</p>

<p>
  <strong>Custom js:</strong>
  <%= @page.custom_js %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Text</th>
      <th>Score</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.name %></td>
        <td><%= review.title %></td>
        <td><%= review.text %></td>
        <td><%= review.score %></td>
        <td><%= review.product_id %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @review.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @review.text %>
</p>

<p>
  <strong>Score:</strong>
  <%= @review.score %>
</p>

<p>
  <strong>Product:</strong>
  <%= @review.product_id %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>